// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC68JQj1VOpRtOJPB10a6AvxXyFv61u-tg',
    appId: '1:381835244896:web:56a08cacc391f3b0de5a05',
    messagingSenderId: '381835244896',
    projectId: 'lab11-6e989',
    authDomain: 'lab11-6e989.firebaseapp.com',
    storageBucket: 'lab11-6e989.appspot.com',
    measurementId: 'G-SD2G45591P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmq3wLDOfuc0DNLZwOGSSZuADy91pT0wM',
    appId: '1:381835244896:android:70e2177a49d69339de5a05',
    messagingSenderId: '381835244896',
    projectId: 'lab11-6e989',
    storageBucket: 'lab11-6e989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQjvv0olO-f9IoYuMTozN_okEdcD41o18',
    appId: '1:381835244896:ios:4cf75e9c9d428eefde5a05',
    messagingSenderId: '381835244896',
    projectId: 'lab11-6e989',
    storageBucket: 'lab11-6e989.appspot.com',
    iosBundleId: 'com.example.lab11',
  );
}
